# Generated by Django 2.0.7 on 2018-11-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app17', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyDetails',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('cno', models.IntegerField()),
                ('subject', models.CharField(max_length=50)),
                ('exp', models.IntegerField()),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
