# Generated by Django 2.1.2 on 2018-11-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('idno', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=5)),
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.IntegerField()),
            ],
        ),
    ]
