# Generated by Django 2.1.2 on 2018-11-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_log_reg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
