# Generated by Django 2.1.2 on 2018-10-31 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqldb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mydb',
            old_name='pnmae',
            new_name='pname',
        ),
    ]
