# Generated by Django 2.1.2 on 2018-10-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqldb', '0002_auto_20181031_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydb',
            name='pno',
            field=models.IntegerField(),
        ),
    ]
