# Generated by Django 2.1.2 on 2018-10-31 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqldb', '0003_auto_20181031_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mydb',
            old_name='pname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='mydb',
            old_name='pno',
            new_name='no',
        ),
        migrations.RenameField(
            model_name='mydb',
            old_name='pprice',
            new_name='price',
        ),
    ]
