# Generated by Django 2.1.2 on 2018-11-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('contact', models.IntegerField()),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
    ]
