# Generated by Django 2.0.7 on 2018-11-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentDetails',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('contact', models.IntegerField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
