# Generated by Django 2.0.7 on 2018-10-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app15', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myproduct',
            name='id',
        ),
        migrations.AlterField(
            model_name='myproduct',
            name='no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
