# Generated by Django 2.1.2 on 2018-11-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commentdetails',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('contact', models.IntegerField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=50)),
            ],
        ),
    ]
